name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg ADMIN_USERNAME=docker --build-arg ADMIN_PASSWORD=docker --build-arg ADMIN_EMAIL=docker@example.com --file Dockerfile -t collapseweb:$(date +%s) .
